title: Project
tabs:
  main:
    display: Main
    sections:
      -
        fields:
          -
            handle: title
            field:
              type: text
              required: true
              validate:
                - required
          -
            handle: description
            field:
              type: markdown
              display: Description
              localizable: true
          -
            handle: images
            field:
              container: assets
              mode: grid
              show_filename: false
              type: assets
              display: Images
  sidebar:
    display: Sidebar
    sections:
      -
        fields:
          -
            handle: slug
            field:
              type: slug
              localizable: true
              validate: 'max:200'
